name: JS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: js
    steps:
    - uses: actions/checkout@v2
    - name: Install
      working-directory: ${{ env.workdir }}
      run: npm install
    - name: Build
      working-directory: ${{ env.workdir }}
      run: npm run build
    - name: Test
      working-directory: ${{ env.workdir }}
      run: npm run test
      env:
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_KEY: ${{ secrets.AWS_KEY }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}
        AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
        AZURE_ACCOUNT: ${{ secrets.AZURE_ACCOUNT }}
        AZURE_KEY: ${{ secrets.AZURE_KEY }}
        RSCONNECT_SERVER: ${{ secrets.RSCONNECT_SERVER }}
        RSCONNECT_KEY: ${{ secrets.RSCONNECT_KEY }}
